service: {{name}}

provider:
  name: aws
  runtime: nodejs8.10

functions:
  echo:
    cljs: {{name}}.core/echo
    events:
      - http:
          path: echo
          method: post

plugins:
  - serverless-cljs-plugin
