language: clojure
sudo: required
dist: trusty
jdk:
- oraclejdk8
before_install:
- sudo apt-get update
- sudo pip install awscli
- which parallel || sudo apt-get install parallel
- nvm install 5
- pushd cljs-lambda; lein install; popd
- pushd plugin;      lein install; popd
- pushd templates/cljs-lambda; lein install; popd
- pushd templates/serverless;  lein install; popd
- lein new cljs-lambda $PROJECT_DIR $SNAPSHOT
- cp -r travis/* $PROJECT_DIR
- pushd cljs-lambda
script: lein doo node test once && popd && pushd $PROJECT_DIR && ./run.sh
env:
  matrix:
  - PROJECT_DIR=test-project-snapshot SNAPSHOT=--snapshot
  global:
  - secure: "I+sPV+UgjqN1ttcvzg4FnTdLhth9rrxqxq+j4+RwV5kx4LQhNcMWFoZJYcGeWxBuBa5ppozPiBl1SeDLyDT8j1ybjXIlhBo13WeoNtvtinvt5xFMJnQwU7LfGwQQStuxhjOVWVtFfpgcCqiulpecihb+Mx73JRJ94WSLhF40hxbSLBGZfr3rwVnn7xIBWnzrMoDwTk9wpGuo2RDztI56J+mows+4Bzw30bYfCU/Gq/fT+1y2rNs1vIBEKGrmNxlr97Bo+l1DNDBlSkpJ0YxF8uLHAfGMO9EznT+sS+hFcfs15Z/9JvvC3iKKiu/UhShsIK2NSF/l2J3ieVCM1b+rHiEgqvuZBfeyRTvAglsEsQ3cvpq6wZuqteb+71nNddoI3C7lzpivyGtfQzB+v8Av++xzAvTClv28+yNOqpNl2cxDdBiDd1W7tX8cDN5PPD+qUJD6pGE2XdKMSv6nqSV/BHam/z4SHcHvXpskQfBFapF+DJRgWP04XJf6SqDZ0U/zRdbB2ubgFy1PYrIk4or2Cz4xXl6+gvxyMGI2uGxpKN+Dv3aT9spEYeLIboEmQV6itK6/KZeNVXTIxc/C6DypCwzF5nBF8Wx6ZZ2NFINqkR/gLY2sQnhHiapNIBxcY1FqvOrJQ5DzM0eGX5hjPN09PhByhU1rZu9DoRFyGdc/qh8="
  - secure: "M4lvtVc5IbosiZoxzxTcol+VgPQDrU+OGzTSvQEW3bgLu4aAh71f9dJME6doxlzz3INNBQobjJOc4vH8xfHkPzYJgpT0uyvdMPb7E6KmiFJkgwr5WY5D/7OGGio7WqhToNqN/tb0kM+2R2WPikO2+EFgNd3OQpXbRZUswzXqHXrf+UFun08PNrdLjCYHeMJzUvEo7dua8wkcvjC7h3nstsaz1ebXGMB7ewZFg1GMuosXAid0gN/v2s5QihXWK6x+kbnsdKiTJDSQOCmX5/g1qx2oCMUlpNQT+LxeZ3aUJXlnRBNYd06z8uektzL9rrbIza8h4oZ7WsXKqBobsEmANTSRFAfee4nUZ5nnEfGSpPKMYuvdysFh5c+Xjmr1f9o7wYLk6/zxsQOHJTilj1mObHTprjZuK9E6SG+Snt4QlI3DUDjhWT2m+BtMGQs118P7EpLJRNni6bhmX6no6f/1P6JD4v4D7DUTh1zkhbPIenI1r33htZyU0g3SAVOZRrWXpUzddSo6Thp/19bpazklFeqQafLxtaRItzeJwaRg4tsKlJr5UXPxmHtT7uFY5esJKbk2vHji7UB0h5+zmYfx6/3jcDNnFtGUjgtdULX3D5zgD/MIQZ4SrHfpbFfyfMRDsKhSJ/V6NFUjGQagusyRO036pQueJi60Krs1a5TIAe4="
